### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by wsdjeg**
add g:var for silent mkdir

move the function to `autoload`,and provide a g:var for silent mkdir

### CODE REVIEW

**Comment by wsdjeg** [comment]
@benizi safe to merge

**Comment by benizi** [comment]
Ugh.  This is why Vim is awful.  There's so much boilerplate to for saving and restoring `'cpo'` and preventing double loading (which isn't really necessary here, since everything's idempotent).  Nonetheless, this is probably an improvement.  Merging.

I'm going to clean up some style afterward, though.  And restore the Vundle directions alongside the Neobundle ones (not everyone uses Unite and friends).

**Comment by benizi** [comment]
Sorry, committed with wrong account. Force-pushed master, but will re-merge this in a minute.

**Comment by benizi** [comment]
Fixed. Thanks again.

New commit: e768c2eedf65b5524399cb9670ba446ebc15424a

**Comment by wsdjeg** [comment]
thanks

**Pull request merged**
